version: '3'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/init-database.sql
    networks:
      - my-network

  amfcrm-app:
    image: eclipse-temurin:17-jre
    build: .
    container_name: amfcrm-container
    ports:
      - "8080:8080"
    volumes:
      - ./target:/target
    command: /bin/sh -c "sleep 5 && java -jar /target/amfcrm-1.0-SNAPSHOT.jar"
    depends_on:
      - mysql-db
    networks:
      - my-network
      
networks:
  my-network:      